# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: ""
email: "epranaykumar@tamu.edu"
description: "Academic website of Pranay Kumar Eadara"
url: "https://epranaykumar.github.io" # GitHub
baseurl: "" # GitHub
github_username: "epranaykumar"
# Build settings
markdown: kramdown
